# Codecov Configuration
# https://docs.codecov.com/docs/codecov-yaml

codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        if_ci_failed: error
        informational: false

    patch:
      default:
        target: auto
        threshold: 1%
        if_ci_failed: error
        informational: false

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "dist/**/*"
  - "node_modules/**/*"
  - "test/**/*"
  - "scripts/**/*"
  - "**/*.d.ts"
  - "**/*.config.*"
  - "src/cli.ts"
  - "src/index.ts"
  - "src/types.ts"

